### ISSUE TITLE
Create empty module

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-LiverAnalysis#1]

**Comment by olevs** [comment]
Added empty extension. How to build:
1. Build Slicer: https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/index.html
2. Build extension: https://www.slicer.org/wiki/Documentation/Nightly/Developers/FAQ/Extensions#How_to_build_an_extension_.3F

**Comment by olevs** [comment]
TODO:
- [x] Add 3d-slicer-extension as a github topic to Slicer-LiverAnalysis repo.
  - Need repo admin rights to do this?
  - Click the settings icon in the right side of "About"
  - See https://github.com/Slicer/ExtensionsIndex/blob/master/.github/PULL_REQUEST_TEMPLATE.md#todo-list-for-submitting-a-new-extension

**Comment by RafaelPalomar** [comment]
Done!
