### ISSUE TITLE
Adding CircleCI configuration file

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-LiverAnalysis#2]
CircleCI will run based on the configuration found on `.circleci` in the root of the project. A good starting point for this should be the `.circleci` file already include on Slicer. Most likely, the Slicer `.circleci` file will be using a container with the required environment; this environment will not directly be useful, because we need a container with the slicer source *built* already to save the computations required to build Slicer.

The project needs to be registered in CircleCI. I believe login to CircleCI through Github OAuth will let any developer to set up the project in CircleCI

- [ ] Enable tests. Either create a Docker image with X support or only create tests that don't need X

**Comment by olevs** [comment]
**CircleCI**:
- Only the owner of the github team/organization can add projects to CircleCI
- All projects use credits, but organizations on the free plan should get more credits for open source builds (https://circleci.com/open-source/)

**3D Slicer on CircleCI**:
- The .circleci in the Slicer repo is only setup to build the Slicer base:
  - The docker image slicer/slicer-base is used
  - The result is stored as an artifact on CircleCI
  - No tests are run
- The Slicer CI prosess is described here:
  - https://blog.kitware.com/3d-slicer-improves-testing-for-pull-requests-using-docker-and-circleci/
  - It appears CircleCI is only used for the first stage, and don't run the whole process 
  - Even though the docker image used by the Slicer repo is only set up to build Slicer core, there are containers for the dependencies, and tests

**Preliminary conclusions:**
- Working on a completely separate Slicer fork/copy probably won't let us use the Slicer CI system
  - It may be possible to mirror the CI system. I don't know how much work that will be yet, as not only CircleCI is involved
  - Creating pull requests from such a separate fork will however allow us the use of The Slicer CI
    - This won't be an optimal solution, and we still may need a CI long before we are ready to add pull requests
- Slicer supports a CI system for extensions, so anything we can put in an extension should be easier to get tested
  - https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html

**Comment by olevs** [comment]
**Current setup:**
Seeing as Slicer deletes the build files in their docker images I have made a new docker image for the ALive project with a built version of Slicer together with the LiverAnalysis plugin, and uploaded this to Docker Hub: olevs/slicer-alive-build
The used Dockerfile is placed in Slicer-LiverAnalysis/Docker/Aliver-build.

I have also created a CircleCI config file that uses this Docker image.
- CircleCI is currently only setup to build the LiverAnalysis plugin.
- Slicer isn't rebuilt (to save time).
- No tests are run. Most Slicer tests are not set up to run without X, and the Docker image isn't set up with X yet. 

**Remaining**
- [x] Turn on CircleCI for Slicer-LiverAnalysis: https://app.circleci.com/projects/project-dashboard/github/ALive-research/
- [x] Enable tests. Either create a Docker image with X support or only create tests that don't need X

**Comment by RafaelPalomar** [comment]
> **Current setup:**
> Seeing as Slicer deletes the build files in their docker images I have made a new docker image for the ALive project with a built version of Slicer together with the LiverAnalysis plugin, and uploaded this to Docker Hub: olevs/slicer-alive-build
> The used Dockerfile is placed in Slicer-LiverAnalysis/Docker/Aliver-build.
> 
> I have also created a CircleCI config file that uses this Docker image.
> 
>     * CircleCI is currently only setup to build the LiverAnalysis plugin.
> 
>     * Slicer isn't rebuilt (to save time).
> 
>     * No tests are run. Most Slicer tests are not set up to run without X, and the Docker image isn't set up with X yet.
> 
> 
> **Remaining**
> 
>     * [x]  Turn on CircleCI for Slicer-LiverAnalysis: https://app.circleci.com/projects/project-dashboard/github/ALive-research/
> 
>     * [ ]  Enable tests. Either create a Docker image with X support or only create tests that don't need X

We can create a virtual monitor to run the tests (e.g., [https://stackoverflow.com/questions/32151043/xvfb-docker-cannot-open-display](https://stackoverflow.com/questions/32151043/xvfb-docker-cannot-open-display))
